### ISSUE TITLE
Something is wrong with pug get version

### ISSUE THREAD

**Issue by fred-jvet** [hoc081098/flutter_google_places#4]
Hi,

I have an error on dependencies

`dependencies:
  flutter:
    sdk: flutter
  flutter_google_places_hoc081098: ^1.0.0-nullsafety.0`

`Error on line 18, column 10 of pubspec.yaml: "version" field must have three numeric components: major, minor, and patch. Instead of "0.1", consider "0.1.0".
   ╷
18 │ version: 0.1
   │          ^^^
   ╵
pub get failed (65;    ╵)`

**Comment by hoc081098** [comment]
Check this commit: https://github.com/hoc081098/Movie-Ticket-Booking/commit/05d568d137d094ec9ca4c124f62b0fb28b3096af. It works well. Can you provide some lines of `pubspec.yaml`

**Comment by fred-jvet** [comment]
Thanks you for helping

I 'm in learning mode :)

I would like to see the exemple works, so i put simply the dependencies

`name: distance_calculator_2
description: Learning

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_google_places_hoc081098: ^1.0.0-nullsafety.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
`

**Comment by hoc081098** [comment]
Hey @fred-jvet , I have found you problem.
**`version: 0.1.0+1`** not `version: 0.1` :))

```yaml
name: distance_calculator_2
description: Learning
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.1.0+1
```

**Comment by fred-jvet** [comment]
Oh...

I focused on a bad thing

World Record... a good story for the aperitif

i go out... :))

Thanks ;)
