### ISSUE TITLE
not wrking

### ISSUE THREAD

**Issue by gauravmehta13** [hoc081098/flutter_google_places#6]
![image](https://user-images.githubusercontent.com/51997260/111875165-610d8680-89be-11eb-8456-b78c9d5168c4.png)
Shows blank screen with this error, PS i dont have any firebase plugins only using google maps not firebase
![image](https://user-images.githubusercontent.com/51997260/111875344-4a1b6400-89bf-11eb-8a57-227be85c9c5d.png)

**Comment by hoc081098** [comment]
Hey, it is issues of `firebase_core_web`, you can check https://github.com/FirebaseExtended/flutterfire/issues/5301

**Comment by gauravmehta13** [comment]
I am not using firebase, the problem started happening after using this package

**Comment by hoc081098** [comment]
From you console, error came from `firebase`, while this package does not use firebase
